version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: "github_token"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing Terraform..."
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install -y terraform
      - terraform version

  pre_build:
    commands:
      - echo "Current directory:"
      - pwd
      - ls -l
      - echo "Fetching Terraform state bucket from Secrets Manager..."
      - export TF_VAR_terraform_state_bucket=$(aws secretsmanager get-secret-value --secret-id aws-tf-state-bucket --query SecretString --output text)
      - export TF_VAR_terraform_state_key="terraform/terraform.tfstate"
      - echo "Initializing Terraform..."
      - terraform -chdir=terraform init -backend-config="bucket=$TF_VAR_terraform_state_bucket" -backend-config="region=$TF_VAR_region" -backend-config="key=$TF_VAR_terraform_state_key"

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform -chdir=terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform changes..."
      - terraform -chdir=terraform apply -auto-approve tfplan

artifacts:
  files:
    - appspec.yml
