version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: "github_token"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Preparing for build..."
      - pwd
      - ls -l

  build:
    commands:
      - echo "Running build phase..."
      - npm run build

  post_build:
    commands:
      - echo "Post build steps..."

artifacts:
  base-directory: nodejsapp
  files:
    - appspec.yml
