version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: "github_token"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix nodejsapp

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - "export REPOSITORY_URI=$REPOSITORY_URI"
      - "export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
      - "echo Repository URI: $REPOSITORY_URI"
      - "echo Image Tag: $IMAGE_TAG"
      - "aws ecr get-login-password --region $TF_VAR_region | docker login --username AWS --password-stdin $REPOSITORY_URI"

  build:
    commands:
      - echo "Building Docker image..."
      - "docker build -t nodejs-app ./nodejsapp"
      - "docker tag nodejs-app $REPOSITORY_URI:$IMAGE_TAG"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - "docker push $REPOSITORY_URI:$IMAGE_TAG"
      - echo "Creating imagedefinitions.json..."
      - "printf '[{\"name\":\"nodejs-app\",\"imageUri\":\"%s\"}]' \"$REPOSITORY_URI:$IMAGE_TAG\" > imagedefinitions.json"

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.m2/**/*'