version: 0.2

phases:
  install:
    commands:
      - echo Installing zip...
      - yum install -y zip
  pre_build:
    commands:
      - echo Pre-build started...
      - mkdir output
  build:
    commands:
      - echo Building source...
      - zip -r ./output/app.zip ./*
  post_build:
    commands:
      - echo Build completed. Deploying to EC2...
      - aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=instanceIds,Values=$EC2_INSTANCE_ID" \
          --parameters 'commands=["mkdir -p /home/ec2-user/app && cd /home/ec2-user/app && aws s3 cp s3://'$DEPLOY_BUCKET'/app.zip . && unzip -o app.zip"]' \
          --region $AWS_DEFAULT_REGION \
          --comment "Deploying build from CodePipeline"

artifacts:
  files:
    - output/app.zip
