version: 0.2

env:
  secrets-manager:
    TF_VAR_github_token: "github_token"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - sudo apt-get update

  pre_build:
    commands:
      - echo "Preparing for build..."
      - pwd
      - ls -l

  build:
    commands:
      - echo "Running build phase..."
      # Add your actual build commands here (e.g. npm install, npm run build)
      - cd /nodejsapp
      - npm install
      - npm run build


  post_build:
    commands:
      - echo "Post build steps..."
      # Add your post-build logic here (e.g. tests, packaging, etc.)

artifacts:
  files:
    - appspec.yml
